/**
 * Writes the compiled ABIs and creation bytecode the browser deploy modals need to
 * packages/quai-service/src/generated/.
 *
 *   pnpm --filter contracts compile && pnpm --filter contracts export:artifacts
 *
 * The modals deploy exactly these bytes, so the files must be regenerated after any contract change. The app's
 * test (tests/deployPlan.test.ts) compares them with the Hardhat artifacts and fails when they are stale.
 */
import * as fs from "fs";
import * as path from "path";
import { loadArtifact } from "./lib/artifacts";

export const EXPORTED = [
    "Qrb",
    "QrbArtifactNFT",
    "CircleswapMasterChef",
    "CircleswapFactory",
    "CircleswapRouter",
    "CircleswapPair",
    "CircleswapTimelock",
    "ERC1967Proxy",
    "UpgradeableBeacon",
    "BeaconProxy"
] as const;

const OUT_DIR = path.resolve(__dirname, "../../quai-service/src/generated");
const NL = String.fromCharCode(10);

function main() {
    fs.mkdirSync(OUT_DIR, { recursive: true });

    const blocks: string[] = [];
    const sizes: string[] = [];
    for (const name of EXPORTED) {
        const a = loadArtifact(name);
        const runtimeBytes = (a.deployedBytecode.length - 2) / 2;
        blocks.push(
            `    ${name}: {` + NL +
                `        abi: ${JSON.stringify(a.abi)} as any[],` + NL +
                `        bytecode: "${a.bytecode}",` + NL +
                `        /** Length in bytes of the runtime code as compiled (immutables zero-filled). */` + NL +
                `        runtimeBytes: ${runtimeBytes}` + NL +
                `    }`
        );
        sizes.push(`    ${name}: ${runtimeBytes}`);
    }

    const artifacts =
        `// GENERATED by packages/contracts/scripts/export-browser-artifacts.ts from the Hardhat artifacts. Do not edit.` + NL +
        `// Regenerate after any contract change: pnpm --filter contracts compile && pnpm --filter contracts export:artifacts` + NL + NL +
        `export const CIRCLESWAP_ARTIFACTS = {` + NL + blocks.join("," + NL) + NL + `} as const;` + NL + NL +
        `export type CircleswapArtifactName = keyof typeof CIRCLESWAP_ARTIFACTS;` + NL;
    fs.writeFileSync(path.join(OUT_DIR, "circleswapArtifacts.ts"), artifacts);

    // Sizes alone: small enough for the start-up check, which must not load the bytecode.
    const runtime =
        `// GENERATED by packages/contracts/scripts/export-browser-artifacts.ts. Do not edit.` + NL +
        `/** Runtime code length in bytes of each compiled contract (immutables zero-filled). */` + NL +
        `export const CIRCLESWAP_RUNTIME_BYTES = {` + NL + sizes.join("," + NL) + NL + `} as const;` + NL;
    fs.writeFileSync(path.join(OUT_DIR, "circleswapRuntimeSizes.ts"), runtime);

    console.log(`Wrote ${OUT_DIR} (artifacts ${(artifacts.length / 1024).toFixed(0)} KiB)`);
}

if (require.main === module) main();
