// The text of registries/deployed.ts for a set of deployed addresses. Identical to what the CLI deploy script
// writes (packages/contracts/scripts/lib/record.ts; tests/deployPlan.test.ts pins the two together), so a browser
// deployment can be committed to the repo exactly like a scripted one.

import type { DeployedAddresses } from '../registries/deployed';
import type { FlowProgress } from './progress';

const ADDRESS = /^0x[0-9a-fA-F]{40}$/;
const ARWEAVE = /^(ar:\/\/|https:\/\/arweave\.net\/)[A-Za-z0-9_-]{43}$/;
const ADDRESS_KEYS = ['QRB', 'QRB_NFT', 'MASTERCHEF', 'AMM_FACTORY', 'AMM_ROUTER'] as const;

export function renderDeployedTs(values: DeployedAddresses): string {
    // These values are written into a source file that ships in the app, so nothing but a plain address or
    // Arweave URI may pass: no quotes, no newlines, nothing that could alter the module.
    for (const key of ADDRESS_KEYS) {
        const v = values[key];
        if (v !== null && !ADDRESS.test(v)) throw new Error(`Refusing to write ${key}: "${v}" is not a full 20-byte address`);
    }
    const uri = values.ARTWORK_URI;
    if (uri !== null && !ARWEAVE.test(uri)) throw new Error(`Refusing to write ARTWORK_URI: "${uri}" is not an Arweave URI`);
    const q = (v: string | null) => (v === null ? 'null' : `'${v}'`);
    return `// Addresses of the Circleswap contracts on Cyprus-1.
//
// GENERATED by packages/contracts/scripts/deploy-quai.ts after a successful --broadcast on cyprus1:
// each address is read off that contract's own deployment receipt, never derived. Until then every
// value is null, and the app treats the contract as not deployed (farms read-only, no QRB balance,
// no Circleswap AMM). Do not hand-edit an address into this file.

export interface DeployedAddresses {
    QRB: string | null;
    QRB_NFT: string | null;
    MASTERCHEF: string | null;
    /** Circleswap AMM factory and router. */
    AMM_FACTORY: string | null;
    AMM_ROUTER: string | null;
    /** Arweave URI the contracts were deployed with. */
    ARTWORK_URI: string | null;
}

export const DEPLOYED: DeployedAddresses = {
    QRB: ${q(values.QRB)},
    QRB_NFT: ${q(values.QRB_NFT)},
    MASTERCHEF: ${q(values.MASTERCHEF)},
    AMM_FACTORY: ${q(values.AMM_FACTORY)},
    AMM_ROUTER: ${q(values.AMM_ROUTER)},
    ARTWORK_URI: ${q(values.ARTWORK_URI)}
};
`;
}

/** Addresses a set of flow progress records has produced, layered over `base` (what is already recorded). */
export function deployedFromProgress(base: DeployedAddresses, flows: Array<FlowProgress | null | undefined>, artworkUri?: string | null): DeployedAddresses {
    const out: DeployedAddresses = { ...base };
    for (const f of flows) {
        if (!f) continue;
        for (const key of ADDRESS_KEYS) {
            const v = f.ctx[key];
            if (v && ADDRESS.test(v)) out[key] = v;
        }
        if (f.ctx.EXISTING_FARM && ADDRESS.test(f.ctx.EXISTING_FARM) && !out.MASTERCHEF) {
            out.MASTERCHEF = f.ctx.EXISTING_FARM;
        }
    }
    if (artworkUri) out.ARTWORK_URI = artworkUri;
    return out;
}
