// Addresses of the Circleswap contracts on Cyprus-1.
//
// GENERATED by packages/contracts/scripts/deploy-quai.ts after a successful --broadcast on cyprus1:
// each address is read off that contract's own deployment receipt, never derived. Until then every
// value is null, and the app treats the contract as not deployed (farms read-only, no QRB balance,
// no Circleswap AMM). Do not hand-edit an address into this file.

export interface DeployedAddresses {
    QRB: string | null;
    QRB_NFT: string | null;
    MASTERCHEF: string | null;
    /** Circleswap AMM factory and router. */
    AMM_FACTORY: string | null;
    AMM_ROUTER: string | null;
    /** Arweave URI the contracts were deployed with. */
    ARTWORK_URI: string | null;
}

export const DEPLOYED: DeployedAddresses = {
    QRB: null,
    QRB_NFT: null,
    MASTERCHEF: null,
    AMM_FACTORY: null,
    AMM_ROUTER: null,
    ARTWORK_URI: null
};
