// Addresses of the Circleswap contracts on Cyprus-1.
//
// GENERATED by packages/contracts/scripts/deploy-quai.ts after a successful --broadcast on cyprus1:
// each address is read off that contract's own deployment receipt, never derived. Until then every
// value is null, and the app treats the contract as not deployed (farms read-only, no QRB balance,
// no Circleswap AMM). Do not hand-edit an address into this file.

export interface DeployedAddresses {
    QRB: string | null;
    QRB_NFT: string | null;
    MASTERCHEF: string | null;
    /** Circleswap AMM factory and router. */
    AMM_FACTORY: string | null;
    AMM_ROUTER: string | null;
    /** Arweave URI the contracts were deployed with. */
    ARTWORK_URI: string | null;
}

export const DEPLOYED: DeployedAddresses = {
    QRB: '0x0050A7fcB00521b75Bb5f3BC8e1D49FED7C08cE5',
    QRB_NFT: '0x000F241469d5E5bb85b1de492c8Fc3796C56d225',
    MASTERCHEF: '0x0061bAC19852dfA0c4AF18d65FCaa9A585e14B86',
    AMM_FACTORY: '0x001563Cc61F495eBF0D7d73Fd054Bc7eE245DD24',
    AMM_ROUTER: '0x00591827868F2989Bb34DbCf71Ff5c48574d4D25',
    ARTWORK_URI: 'ar://MbJXaZJwc0PjrCK2iwBblrR6m0aAYIUJ7xsIIpQpHQk'
};
