import type { CircleswapDeployment } from "./circleswap";
import type { AmmDeployment } from "./amm";

export interface DeployedRecordValues {
    QRB: string | null;
    QRB_NFT: string | null;
    MASTERCHEF: string | null;
    AMM_FACTORY: string | null;
    AMM_ROUTER: string | null;
    /** Arweave URI the contracts were deployed with. */
    ARTWORK_URI: string | null;
}

/** Source of packages/quai-service/src/registries/deployed.ts for the given deployment. */
export function renderDeployedTs(addresses: DeployedRecordValues): string {
    // These values are written into a source file that ships in the app, so nothing but a plain address or
    // Arweave URI may pass: no quotes, no newlines, nothing that could alter the module.
    const addr = /^0x[0-9a-fA-F]{40}$/;
    for (const key of ["QRB", "QRB_NFT", "MASTERCHEF", "AMM_FACTORY", "AMM_ROUTER"] as const) {
        const v = addresses[key];
        if (v !== null && !addr.test(v)) throw new Error(`Refusing to write ${key}: "${v}" is not a full 20-byte address`);
    }
    const uri = addresses.ARTWORK_URI;
    if (uri !== null && !/^(ar:\/\/|https:\/\/arweave\.net\/)[A-Za-z0-9_-]{43}$/.test(uri)) {
        throw new Error(`Refusing to write ARTWORK_URI: "${uri}" is not an Arweave URI`);
    }
    const q = (v: string | null) => (v === null ? "null" : `'${v}'`);
    return `// Addresses of the Circleswap contracts on Cyprus-1.
//
// GENERATED by packages/contracts/scripts/deploy-quai.ts after a successful --broadcast on cyprus1:
// each address is read off that contract's own deployment receipt, never derived. Until then every
// value is null, and the app treats the contract as not deployed (farms read-only, no QRB balance,
// no Circleswap AMM). Do not hand-edit an address into this file.

export interface DeployedAddresses {
    QRB: string | null;
    QRB_NFT: string | null;
    MASTERCHEF: string | null;
    /** Circleswap AMM factory and router. */
    AMM_FACTORY: string | null;
    AMM_ROUTER: string | null;
    /** Arweave URI the contracts were deployed with. */
    ARTWORK_URI: string | null;
}

export const DEPLOYED: DeployedAddresses = {
    QRB: ${q(addresses.QRB)},
    QRB_NFT: ${q(addresses.QRB_NFT)},
    MASTERCHEF: ${q(addresses.MASTERCHEF)},
    AMM_FACTORY: ${q(addresses.AMM_FACTORY)},
    AMM_ROUTER: ${q(addresses.AMM_ROUTER)},
    ARTWORK_URI: ${q(addresses.ARTWORK_URI)}
};
`;
}

/** JSON-safe record of a broadcast deployment (bigints as strings). */
export function deploymentRecord(network: string, chainId: bigint, deployer: string, artworkURI: string, d: CircleswapDeployment) {
    const one = (r: { address?: string; txHash?: string; blockNumber?: number; gasUsed?: bigint; gasLimit: bigint } | undefined) =>
        r && {
            address: r.address,
            txHash: r.txHash,
            blockNumber: r.blockNumber,
            gasUsed: r.gasUsed?.toString(),
            gasLimit: r.gasLimit.toString()
        };
    return {
        network,
        chainId: chainId.toString(),
        deployer,
        artworkURI,
        deployedAt: new Date().toISOString(),
        qrb: one(d.qrb),
        qrbAddress: d.qrbAddress ?? null,
        qrbArtifactNft: one(d.nft),
        masterChef: one(d.farm),
        minted: d.minted ?? null
    };
}

/** JSON-safe record of a broadcast AMM deployment. */
export function ammRecord(network: string, chainId: bigint, deployer: string, owner: string, d: AmmDeployment) {
    const one = (r: { address?: string; txHash?: string; blockNumber?: number; gasUsed?: bigint; gasLimit: bigint }) => ({
        address: r.address,
        txHash: r.txHash,
        blockNumber: r.blockNumber,
        gasUsed: r.gasUsed?.toString(),
        gasLimit: r.gasLimit.toString()
    });
    return {
        network,
        chainId: chainId.toString(),
        deployer,
        owner,
        deployedAt: new Date().toISOString(),
        factory: one(d.factory),
        router: one(d.router),
        probePoolAddress: d.probePoolAddress ?? null
    };
}
